#!/usr/bin/env python3
"""Per-robot VLM semantic perception agent for Stage-5.

Each node owns one robot's latest RGB-D/pose context. A synchronous coordinator
requests an interpretation only at a geometry/coverage/query trigger. Exactly
one best current RGB frame is sent to the VLM; no visual clips are transmitted.
"""
from __future__ import annotations

import copy
import os
import sys
import threading
import time
from typing import Any, Dict, List, Optional

import cv2
import numpy as np
import rospy
from cv_bridge import CvBridge
from geometry_msgs.msg import PoseStamped
from nav_msgs.msg import OccupancyGrid
from sensor_msgs.msg import CameraInfo, Image
from std_msgs.msg import Bool, String

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

from vlm_common import (OpenAICompatibleVisionClient, compact_json, grid_from_msg,
                        image_quality_score, mock_local_report, normalize_bbox,
                        pixel_depth_to_map, pose_to_dict, sampled_depth_coverage_cells,
                        safe_json_loads, valid_depth_m)


LOCAL_SYSTEM_PROMPT = """You are a robot-local visual semantic perception module for indoor search-and-rescue.
Return ONLY one valid JSON object. Do not invent objects that are not visible. You are not a controller.

Important output rules:

1. "target_evidence" is query-specific. It should describe whether the current target query is visible.
2. "entities" is query-agnostic. It must include salient visible objects or landmarks even if they are NOT the current target.
3. Always include visually salient colored objects in "entities", especially red, blue, green, yellow, black, white, or other distinctive objects.
4. If a visible object does not match the current target query, keep it in "entities" with its true "appearance_color", but do not mark it as target_evidence.
5. The values of "scene_summary" and "target_evidence.reason" MUST be concise Chinese descriptions.
6. Do not write English sentences in "scene_summary" or "target_evidence.reason".

All values of "scene_summary" and "target_evidence.reason" MUST be written in concise Chinese.
Do not use English sentences for these two fields.

Use this schema:
{
  "scene_summary": "简短中文场景描述",
  "entities": [{"label":"doorway|table|chair|cabinet|bed|stairs|corridor|room_entry|obstacle|other",
                  "category":"topological_landmark|furniture|obstacle|other",
                  "bbox":[x0,y0,x1,y1], "confidence":0.0,
                  "appearance_color":"red|blue|green|yellow|other|unknown",
                  "navigation_effect":"new_room_access|occlusion_region|low_obstacle|none"}],
  "target_evidence": {"state":"NONE|POSSIBLE|LIKELY", "confidence":0.0,
                      "bbox":[x0,y0,x1,y1] or null, "reason":"简短中文判断依据"},
  "requested_follow_up":"none|ground_verify|aerial_overwatch|inspect_doorway"
}

Target relevance and object category are independent.
Do not require the queried target to belong to a specific semantic class such as
person, furniture, or obstacle. A detected object may remain labeled as
"obstacle", "other", "cylinder", or another scene entity while still being
reported as target_evidence.
When an object's visible appearance substantially matches target_query.target_attributes,
especially its requested color, return target_evidence.state as POSSIBLE or LIKELY
with a tight bbox, even if its semantic category is uncertain.
Use NONE only when no visible object plausibly matches the requested appearance.

Bounding boxes must be pixel coordinates in the provided image.

When event_reason starts with COLOR_CANDIDATE_, the prompt includes a
color_candidate_hint generated by a lightweight HSV detector.

The color candidate is only a visual proposal, not proof of a target.
Carefully inspect the marked candidate region and decide whether it is:

1. evidence relevant to the current target query;
2. an ordinary colored object;
3. a red obstacle, furniture item, or irrelevant object;
4. a false detection.

If the color candidate is a real visible object but does not match the current
target query, still include it in entities with label "other" and preserve its
appearance_color. """


class LocalVLMPerception:
    def __init__(self):
        self.robot_name = rospy.get_param('~robot')
        root = rospy.get_param('/vlm_semantic_search')
        self.root = root
        self.local_cfg = root['local_perception']
        all_robots = list(rospy.get_param('/vehicles', [])) + list(rospy.get_param('/ground_robots', []))
        self.robot = next((r for r in all_robots if r.get('name') == self.robot_name), None)
        if self.robot is None:
            raise RuntimeError('Unknown robot %s' % self.robot_name)
        self.map_key = 'ugv' if self.robot.get('type') == 'ugv' else 'uav'
        self.lock = threading.RLock()
        self.bridge = CvBridge()
        self.pose: Optional[PoseStamped] = None
        self.image: Optional[np.ndarray] = None
        self.depth: Optional[np.ndarray] = None
        self.camera_info: Optional[CameraInfo] = None
        self.maps: Dict[str, Optional[OccupancyGrid]] = {'uav': None, 'ugv': None}
        self.current_query: Dict[str, Any] = dict(root.get('target_query', {}))
        self.color_snapshot_cv = threading.Condition(self.lock)
        self.color_snapshots: Dict[str, Dict[str, Any]] = {}
        self.color_snapshot_order: List[str] = []
        self.color_snapshot_cache_size = max(2,int(
                root.get('scheduler', {}).get('color_candidate_trigger', {}).get('snapshot_cache_size', 8,)),)
        self.client = OpenAICompatibleVisionClient(root['backend'])
        self.pub = rospy.Publisher('/vlm/local_semantic_observation', String, queue_size=10)
        self.debug_pub = rospy.Publisher('/%s/vlm/debug_image' % self.robot_name, Image, queue_size=1, latch=True)
        # Latched startup handshake. The scheduler waits for all robots before it
        # emits the first epoch, preventing a launch-order race that skipped
        # uav1/ugv0 initial debug images.
        self.ready_pub = rospy.Publisher('/%s/vlm/ready' % self.robot_name, Bool, queue_size=1, latch=True)

        rospy.Subscriber(self.robot['global_pose_topic'], PoseStamped, self._pose_cb, queue_size=20)
        rospy.Subscriber(self.robot['rgb_topic'], Image, self._rgb_cb, queue_size=1, buff_size=2**24)
        rospy.Subscriber(self.robot['depth_topic'], Image, self._depth_cb, queue_size=1, buff_size=2**24)
        rospy.Subscriber(self.robot['camera_info_topic'], CameraInfo, self._info_cb, queue_size=2, buff_size=2**20)
        rospy.Subscriber('/global_map_2d', OccupancyGrid, lambda msg: self._map_cb('uav', msg), queue_size=2)
        rospy.Subscriber('/ugv0/ground_map_2d', OccupancyGrid, lambda msg: self._map_cb('ugv', msg), queue_size=2)
        rospy.Subscriber('/vlm/target_query', String, self._query_cb, queue_size=3)
        rospy.Subscriber('/vlm/local_perception_request', String, self._request_cb, queue_size=10)
        snapshot_ns = '/%s/vlm/color_snapshot' % (
            self.robot_name
        )

        rospy.Subscriber(
            snapshot_ns + '/rgb',
            Image,
            self._color_snapshot_rgb_cb,
            queue_size=4,
            buff_size=2**24,
        )

        rospy.Subscriber(
            snapshot_ns + '/depth',
            Image,
            self._color_snapshot_depth_cb,
            queue_size=4,
            buff_size=2**24,
        )

        rospy.Subscriber(
            snapshot_ns + '/camera_info',
            CameraInfo,
            self._color_snapshot_info_cb,
            queue_size=4,
        )

        rospy.Subscriber(
            snapshot_ns + '/pose_map',
            PoseStamped,
            self._color_snapshot_pose_cb,
            queue_size=4,
        )

        rospy.Subscriber(
            snapshot_ns + '/meta',
            String,
            self._color_snapshot_meta_cb,
            queue_size=4,
        )
        self.ready_pub.publish(True)
        rospy.loginfo('Local VLM perception node ready for %s. RGB=%s', self.robot_name, self.robot['rgb_topic'])

    def _pose_cb(self, msg):
        with self.lock:
            self.pose = msg

    def _rgb_cb(self, msg):
        try:
            image = self.bridge.imgmsg_to_cv2(msg, desired_encoding='bgr8')
        except Exception:
            return
        with self.lock:
            self.image = np.array(image, copy=True)

    def _depth_cb(self, msg):
        try:
            depth = self.bridge.imgmsg_to_cv2(msg, desired_encoding='passthrough')
        except Exception:
            return
        with self.lock:
            self.depth = np.array(depth, copy=True)

    def _info_cb(self, msg):
        with self.lock:
            self.camera_info = msg

    def _map_cb(self, key, msg):
        with self.lock:
            self.maps[key] = msg

    def _query_cb(self, msg):
        parsed = safe_json_loads(msg.data, None)
        if isinstance(parsed, dict):
            with self.lock:
                self.current_query = parsed

    def _request_cb(self, msg):
        request = safe_json_loads(msg.data, None)
        if not isinstance(request, dict):
            return
        if self.robot_name not in request.get('participants', []):
            return
        thread = threading.Thread(target=self._process, args=(request,), daemon=True)
        thread.start()

    def _snapshot(self):
        with self.lock:
            return (self.image.copy() if self.image is not None else None,
                    self.depth.copy() if self.depth is not None else None,
                    self.camera_info, self.pose, self.maps.get(self.map_key), dict(self.current_query))
    
    @staticmethod
    def _snapshot_id_from_header(msg) -> str:
        return str(
            msg.header.frame_id or ''
        )

    def _trim_color_snapshot_cache_locked(
            self
    ) -> None:
        while (
            len(self.color_snapshot_order)
            > self.color_snapshot_cache_size
        ):
            old_id = self.color_snapshot_order.pop(0)
            self.color_snapshots.pop(
                old_id,
                None,
            )

    def _store_color_snapshot_part(
            self,
            snapshot_id: str,
            key: str,
            value: Any
    ) -> None:
        if not snapshot_id:
            return

        with self.color_snapshot_cv:
            entry = self.color_snapshots.setdefault(
                snapshot_id,
                {},
            )

            if snapshot_id not in self.color_snapshot_order:
                self.color_snapshot_order.append(
                    snapshot_id
                )

            entry[key] = value

            self._trim_color_snapshot_cache_locked()

            self.color_snapshot_cv.notify_all()

    def _color_snapshot_rgb_cb(
            self,
            msg: Image
    ) -> None:
        snapshot_id = self._snapshot_id_from_header(msg)

        if not snapshot_id:
            return

        try:
            image = self.bridge.imgmsg_to_cv2(
                msg,
                desired_encoding='bgr8',
            )
        except Exception:
            return

        self._store_color_snapshot_part(
            snapshot_id,
            'image',
            np.array(image, copy=True),
        )

    def _color_snapshot_depth_cb(
            self,
            msg: Image
    ) -> None:
        snapshot_id = self._snapshot_id_from_header(msg)

        if not snapshot_id:
            return

        try:
            depth = self.bridge.imgmsg_to_cv2(
                msg,
                desired_encoding='passthrough',
            )
        except Exception:
            return

        self._store_color_snapshot_part(
            snapshot_id,
            'depth',
            np.array(depth, copy=True),
        )

    def _color_snapshot_info_cb(
            self,
            msg: CameraInfo
    ) -> None:
        snapshot_id = self._snapshot_id_from_header(msg)

        if not snapshot_id:
            return

        self._store_color_snapshot_part(
            snapshot_id,
            'camera_info',
            copy.deepcopy(msg),
        )

    def _color_snapshot_pose_cb(
            self,
            msg: PoseStamped
    ) -> None:
        snapshot_id = self._snapshot_id_from_header(msg)

        if not snapshot_id:
            return

        self._store_color_snapshot_part(
            snapshot_id,
            'pose',
            copy.deepcopy(msg),
        )

    def _color_snapshot_meta_cb(
            self,
            msg: String
    ) -> None:
        meta = safe_json_loads(
            msg.data,
            None,
        )

        if not isinstance(meta, dict):
            return

        snapshot_id = str(
            meta.get('snapshot_id', '')
        )

        if not snapshot_id:
            return

        self._store_color_snapshot_part(
            snapshot_id,
            'meta',
            dict(meta),
        )

    def _get_color_snapshot(
            self,
            snapshot_id: str
    ):
        """Wait briefly until all components of the frozen RGB-D snapshot arrive."""

        wait_sec = max(
            0.1,
            float(
                self.root.get(
                    'scheduler',
                    {}
                ).get(
                    'color_candidate_trigger',
                    {}
                ).get(
                    'snapshot_transport_wait_sec',
                    1.0,
                )
            ),
        )

        deadline = time.monotonic() + wait_sec

        required = {
            'image',
            'depth',
            'camera_info',
            'pose',
            'meta',
        }

        with self.color_snapshot_cv:
            while not rospy.is_shutdown():
                entry = self.color_snapshots.get(
                    snapshot_id,
                    {},
                )

                if required.issubset(
                    set(entry.keys())
                ):
                    return (
                        entry['image'].copy(),
                        entry['depth'].copy(),
                        copy.deepcopy(
                            entry['camera_info']
                        ),
                        copy.deepcopy(entry['pose']),
                        dict(entry['meta']),
                    )

                remain = deadline - time.monotonic()

                if remain <= 0.0:
                    break

                self.color_snapshot_cv.wait(
                    timeout=min(
                        0.05,
                        remain,
                    )
                )

        return None

    def _annotate_color_candidate(
            self,
            image: np.ndarray,
            candidate: Optional[Dict[str, Any]]
    ) -> np.ndarray:
        """Draw the HSV candidate box before sending the image to Local VLM.

        The second argument is the color-candidate dictionary itself, rather than
        the complete trigger request. For ordinary VLM events it may be None.
        """

        if image is None:
            return image

        if not isinstance(candidate, dict):
            return image

        raw_bbox = candidate.get('bbox')

        if (
            not isinstance(raw_bbox, (list, tuple))
            or len(raw_bbox) != 4
        ):
            return image

        try:
            x0, y0, x1, y1 = [
                int(round(float(value)))
                for value in raw_bbox
            ]
        except (TypeError, ValueError):
            return image

        height, width = image.shape[:2]

        x0 = max(0, min(width - 1, x0))
        y0 = max(0, min(height - 1, y0))
        x1 = max(0, min(width - 1, x1))
        y1 = max(0, min(height - 1, y1))

        if x1 <= x0 or y1 <= y0:
            return image

        annotated = image.copy()

        cv2.rectangle(
            annotated,
            (x0, y0),
            (x1, y1),
            (255, 0, 255),
            3,
        )

        label = 'HSV %s candidate - verify' % (
            str(candidate.get('color', 'unknown'))
        )

        cv2.putText(
            annotated,
            label,
            (x0, max(22, y0 - 8)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.56,
            (255, 0, 255),
            2,
        )

        return annotated

    def _prompt(
            self,
            request: Dict[str, Any],
            query: Dict[str, Any],
            pose: Optional[PoseStamped],
            quality: float
    ) -> str:
        details = request.get('details', {})

        if not isinstance(details, dict):
            details = {}

        color_candidate = details.get(
            'color_candidate'
        )

        return compact_json({
            'robot_id': self.robot_name,
            'robot_type': self.robot.get('type'),
            'event_reason': request.get('reason'),
            'target_query': query,
            'robot_pose_map': pose_to_dict(pose),
            'image_quality_laplacian': round(
                quality,
                2,
            ),

            # 颜色检测只是候选建议，不是最终目标判定。
            'color_candidate_hint': color_candidate,

            'instruction': (
                'Describe visually supported scene entities and evidence. '
                'The target_evidence field is query-specific and should only describe '
                'whether the current target query is visible. '

                'The entities list is query-agnostic: include salient visible objects, '
                'landmarks, obstacles, passages, doorways, colored objects, boxes, cylinders, '
                'or other distinctive objects even if they do not match the current target. '
                'For every colored object, preserve its true appearance_color such as red, '
                'blue, green, yellow, other, or unknown. '

                'Target relevance is independent from semantic category: an object may remain '
                'obstacle, other, cylinder, or box while still being a possible target if its '
                'visible color or appearance matches the current query. '

                'If color_candidate_hint exists, inspect its marked bbox carefully and '
                'explicitly confirm or reject its relevance to the current target query. '

                'Write scene_summary and target_evidence.reason in concise Chinese. '
                'Do not use English sentences for these two fields.'
            ),
        })

    def _call(self, image: np.ndarray, prompt: str, query: Dict[str, Any], quality: float,
              timeout_sec: Optional[float] = None) -> Dict[str, Any]:
        mode = str(self.root['backend'].get('mode', 'mock')).lower()
        if mode == 'mock':
            return mock_local_report(query, image.shape[:2], quality)
        try:
            return self.client.complete_json(
                LOCAL_SYSTEM_PROMPT, prompt, image,
                int(self.local_cfg.get('jpeg_quality', 85)),
                timeout_sec=timeout_sec)
        except Exception as exc:
            if bool(self.root['backend'].get('allow_mock_fallback', True)):
                result = mock_local_report(query, image.shape[:2], quality)
                result['backend_error'] = repr(exc)
                return result
            raise

    @staticmethod
    def _retryable_backend_error(exc: Exception, retry_cfg: Dict[str, Any]) -> bool:
        """Classify transient cloud failures that may benefit from one retry.

        Configuration/request errors (401, 403, 400, 404 and malformed JSON) are
        deliberately not retried.  The same epoch snapshot is used on every
        retry, so all successful robot reports remain temporally comparable.
        """
        text = repr(exc).lower()
        if 'http 401' in text or 'http 403' in text or 'http 400' in text or 'http 404' in text:
            return False
        if 'does not contain a valid json object' in text:
            return False
        if ('timeout' in text or 'timed out' in text):
            return bool(retry_cfg.get('retry_on_timeout', True))
        if ('connection reset' in text or 'connection aborted' in text or
                'remote end closed' in text or 'temporarily unavailable' in text or
                'urlerror' in text or 'connection refused' in text):
            return bool(retry_cfg.get('retry_on_connection_errors', True))
        if any(('http %s' % code) in text for code in ('429', '500', '502', '503', '504')):
            return bool(retry_cfg.get('retry_on_http_429_5xx', True))
        return False

    def _call_with_retry(self, image: np.ndarray, prompt: str, query: Dict[str, Any],
                         quality: float, epoch_id: str) -> Dict[str, Any]:
        """Call the backend with bounded retry using the exact same snapshot.

        `image` and `prompt` are created once in `_process` before this method.
        Retries never re-read ROS topics, re-encode another camera frame, or
        alter JPEG quality/model tokens.  They only repeat the same request after
        a bounded wall-clock backoff.
        """
        retry_cfg = self.root.get('local_retry', {})
        enabled = bool(retry_cfg.get('enabled', False))
        max_retries = max(0, int(retry_cfg.get('max_retries', 0))) if enabled else 0
        base_timeout = float(self.root.get('backend', {}).get('timeout_sec', 20.0))
        attempt_timeout = float(retry_cfg.get('attempt_timeout_sec', base_timeout))
        attempt_timeout = max(0.1, attempt_timeout)
        total_deadline = max(attempt_timeout, float(retry_cfg.get('total_deadline_sec', attempt_timeout)))
        initial_backoff = max(0.0, float(retry_cfg.get('initial_backoff_sec', 0.0)))
        multiplier = max(1.0, float(retry_cfg.get('backoff_multiplier', 2.0)))
        start_wall = time.monotonic()
        last_exc: Optional[Exception] = None
        attempts_made = 0

        for attempt in range(1, max_retries + 2):
            attempts_made = attempt
            remaining = total_deadline - (time.monotonic() - start_wall)
            if remaining <= 0.0:
                break
            per_attempt_timeout = min(attempt_timeout, remaining)
            try:
                result = self._call(image, prompt, query, quality, timeout_sec=per_attempt_timeout)
                result['_retry_attempt_count'] = attempt
                result['_retry_count'] = attempt - 1
                result['_retry_total_deadline_sec'] = total_deadline
                return result
            except Exception as exc:
                last_exc = exc
                can_retry = attempt <= max_retries and self._retryable_backend_error(exc, retry_cfg)
                if not can_retry:
                    break
                backoff = initial_backoff * (multiplier ** (attempt - 1))
                remaining_after_failure = total_deadline - (time.monotonic() - start_wall)
                if remaining_after_failure <= backoff:
                    break
                rospy.logwarn(
                    'Local VLM %s attempt %d/%d failed in epoch %s; retrying identical snapshot in %.1fs: %s',
                    self.robot_name, attempt, max_retries + 1, epoch_id, backoff, repr(exc))
                if backoff > 0.0:
                    time.sleep(backoff)

        if last_exc is None:
            raise RuntimeError('VLM request exhausted retry deadline without a backend response.')
        raise RuntimeError('VLM request failed after %d attempt(s): %r' % (max(1, attempts_made), last_exc))

    def _entity_positions(self, entities: List[Dict[str, Any]], image: np.ndarray, depth: np.ndarray,
                          info: CameraInfo, pose: PoseStamped) -> List[Dict[str, Any]]:
        processed = []
        h, w = image.shape[:2]
        for index, raw in enumerate(entities if isinstance(entities, list) else []):
            if not isinstance(raw, dict):
                continue
            bbox = normalize_bbox(raw.get('bbox'), w, h)
            if bbox is None:
                continue
            u = (bbox[0] + bbox[2]) // 2
            v = (bbox[1] + bbox[3]) // 2
            d = valid_depth_m(depth, u, v, int(self.local_cfg.get('depth_patch_radius_px', 4)),
                              float(self.local_cfg.get('min_depth_m', 0.30)), float(self.local_cfg.get('max_depth_m', 8.0)))
            point = pixel_depth_to_map(self.robot, pose, info, u, v, d) if d is not None else None
            item = {
                'object_id': '%s_%s_%02d' % (self.robot_name, str(raw.get('label', 'object')), index),
                'label': str(raw.get('label', 'other')),
                'category': str(raw.get('category', 'other')),
                'appearance_color': str(raw.get('appearance_color', 'unknown')),  # 新增：保留对象的外观颜色。
                'bbox': bbox,
                'confidence': float(raw.get('confidence', 0.0)),
                'navigation_effect': str(raw.get('navigation_effect', 'none')),
                'position_map': ({'x': round(point[0], 3), 'y': round(point[1], 3), 'z': round(point[2], 3)}
                                 if point is not None else None),
            }
            processed.append(item)
        return processed

    def _target_position(self, evidence: Dict[str, Any], image: np.ndarray, depth: np.ndarray,
                         info: CameraInfo, pose: PoseStamped) -> Dict[str, Any]:
        h, w = image.shape[:2]
        result = dict(evidence) if isinstance(evidence, dict) else {}
        bbox = normalize_bbox(result.get('bbox'), w, h)
        result['bbox'] = bbox
        if bbox is None:
            return result
        u = (bbox[0] + bbox[2]) // 2
        v = (bbox[1] + bbox[3]) // 2
        d = valid_depth_m(depth, u, v, int(self.local_cfg.get('depth_patch_radius_px', 4)),
                          float(self.local_cfg.get('min_depth_m', 0.30)), float(self.local_cfg.get('max_depth_m', 8.0)))
        point = pixel_depth_to_map(self.robot, pose, info, u, v, d) if d is not None else None
        result['position_map'] = ({'x': round(point[0], 3), 'y': round(point[1], 3), 'z': round(point[2], 3)}
                                  if point is not None else None)
        result['depth_m'] = d
        return result

    def _debug(self, image: np.ndarray, entities: List[Dict[str, Any]], target: Dict[str, Any]) -> None:
        if not bool(self.local_cfg.get('publish_debug_image', True)):
            return
        debug = image.copy()
        for e in entities:
            x0, y0, x1, y1 = e['bbox']
            cv2.rectangle(debug, (x0, y0), (x1, y1), (0, 255, 255), 2)
            cv2.putText(debug, e['label'], (x0, max(15, y0-4)), cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 255, 255), 1)
        bbox = target.get('bbox') if isinstance(target, dict) else None
        if bbox is not None:
            x0, y0, x1, y1 = bbox
            cv2.rectangle(debug, (x0, y0), (x1, y1), (0, 0, 255), 2)
            cv2.putText(debug, 'query evidence', (x0, max(15, y0-4)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)
        try:
            self.debug_pub.publish(self.bridge.cv2_to_imgmsg(debug, encoding='bgr8'))
        except Exception:
            pass

    def _process(self, request: Dict[str, Any]) -> None:
        live_image, live_depth, live_info, live_pose, map_msg, live_query = self._snapshot()

        details = request.get('details', {})

        if not isinstance(details, dict):
            details = {}

        color_candidate = details.get(
            'color_candidate'
        )

        if not isinstance(color_candidate, dict):
            color_candidate = None

        snapshot_id = ''

        if color_candidate is not None:
            snapshot_id = str(
                color_candidate.get(
                    'snapshot_id',
                    details.get(
                        'snapshot_id',
                        '',
                    ),
                )
            )

        image = live_image
        depth = live_depth
        info = live_info
        pose = live_pose
        snapshot_meta = None
        visual_context_source = 'LIVE_CONTEXT'

        # COLOR_CANDIDATE event 必须优先使用检测时冻结的 RGB-D/位姿。
        if snapshot_id:
            frozen = self._get_color_snapshot(
                snapshot_id
            )

            if frozen is not None:
                image, depth, info, pose, snapshot_meta = frozen
                visual_context_source = (
                    'FROZEN_COLOR_CANDIDATE_SNAPSHOT'
                )

                rospy.loginfo(
                    'Local VLM %s uses frozen color snapshot %s.',
                    self.robot_name,
                    snapshot_id,
                )
            else:
                rospy.logwarn(
                    'Local VLM %s cannot retrieve frozen snapshot %s; '
                    'falling back to live camera context.',
                    self.robot_name,
                    snapshot_id,
                )

        query = dict(live_query)

        requested_query = request.get('query')

        if isinstance(requested_query, dict):
            query = dict(requested_query)

        epoch_id = request.get('epoch_id', '')

        base = {
            'epoch_id': epoch_id,
            'robot_id': self.robot_name,
            'robot_type': self.robot.get('type'),
            'query_version': int(
                query.get('query_version', 0)
            ),
            'query': query,

            # 用于验证 Local VLM 是否真正用了冻结时刻的图像。
            'visual_context_source': visual_context_source,
            'color_snapshot_id': (
                snapshot_id or None
            ),
            'color_snapshot_meta': snapshot_meta,
        }
        if image is None or depth is None or info is None or pose is None:
            base.update({'status': 'NO_VISUAL_CONTEXT', 'entities': [], 'target_evidence': {'state': 'UNKNOWN', 'confidence': 0.0},
                         'coverage_cells': []})
            self.pub.publish(compact_json(base))
            return
        quality = image_quality_score(image)
        grid = grid_from_msg(map_msg)
        coverage = sampled_depth_coverage_cells(
            self.robot, pose, info, depth, grid,
            int(self.local_cfg.get('coverage_depth_stride_px', 32)),
            float(self.local_cfg.get('min_depth_m', 0.30)), float(self.local_cfg.get('max_depth_m', 8.0)),
            int(self.local_cfg.get('max_coverage_cells', 280)))
        prompt = self._prompt(request, query, pose, quality)
        vlm_image = self._annotate_color_candidate(image, color_candidate,)
        # vlm_image = self._annotate_color_candidate(image, request)
        try:
            report = self._call_with_retry(
                vlm_image,
                prompt,
                query,
                quality,
                epoch_id,
            )
            entities = self._entity_positions(report.get('entities', []), image, depth, info, pose)
            target = self._target_position(report.get('target_evidence', {}), image, depth, info, pose)
            backend_error = report.get('backend_error')
            status = 'BACKEND_FALLBACK' if backend_error else 'OK'
            base.update({
                'status': status, 'scene_summary': str(report.get('scene_summary', '')),
                'entities': entities, 'target_evidence': target,
                'requested_follow_up': str(report.get('requested_follow_up', 'none')),
                'observation_quality': round(float(report.get('observation_quality', min(1.0, quality/100.0))), 3),
                'pose_map': pose_to_dict(pose), 'coverage_cells': coverage,
                'trigger_reason': request.get('reason'),
                'vlm_attempt_count': int(report.get('_retry_attempt_count', 1)),
                'vlm_retry_count': int(report.get('_retry_count', 0)),
            })
            if backend_error:
                base['backend_error'] = str(backend_error)
            self._debug(image, entities, target)
            self.pub.publish(compact_json(base))
            if backend_error:
                rospy.logwarn('Local VLM %s fallback for epoch %s: %s', self.robot_name, epoch_id, backend_error)
            else:
                rospy.loginfo('Local VLM %s completed epoch %s with %d entities.', self.robot_name, epoch_id, len(entities))
        except Exception as exc:
            error_text = repr(exc)
            status = 'BACKEND_TIMEOUT' if 'timeout' in error_text.lower() else 'BACKEND_ERROR'
            target = {'state': 'UNKNOWN', 'confidence': 0.0, 'bbox': None,
                      'reason': 'local VLM backend unavailable'}
            base.update({
                'status': status,
                'scene_summary': 'No local VLM interpretation was produced because the backend request failed.',
                'entities': [], 'target_evidence': target,
                'requested_follow_up': 'none',
                'observation_quality': round(min(1.0, float(quality) / 100.0), 3),
                'pose_map': pose_to_dict(pose), 'coverage_cells': coverage,
                'trigger_reason': request.get('reason'), 'backend_error': error_text,
                'vlm_retry_enabled': bool(self.root.get('local_retry', {}).get('enabled', False)),
                'vlm_max_retries': int(self.root.get('local_retry', {}).get('max_retries', 0)),
            })
            self._debug(image, [], target)
            self.pub.publish(compact_json(base))
            rospy.logwarn('Local VLM %s failed epoch %s: %s', self.robot_name, epoch_id, error_text)


def main():
    rospy.init_node('local_vlm_perception')
    LocalVLMPerception()
    rospy.spin()


if __name__ == '__main__':
    main()
