#!/usr/bin/env python3
"""Map-frame Go2 proxy executor with A* waypoint-route tracking.

The high level layer sends a ``nav_msgs/Path`` generated by the deterministic
post-selection A* planner.  This node tracks intermediate waypoints instead of
directly steering toward the final endpoint behind a wall.  The legacy single
``mission_goal`` topic remains supported for manual/debug commands.
"""
from __future__ import annotations

import json
import math
import threading
import time
from typing import List

import rospy
from geometry_msgs.msg import PoseStamped, Twist
from nav_msgs.msg import Path
from std_msgs.msg import Bool, String
from tf.transformations import euler_from_quaternion


class UGVWaypointExecutor:
    def __init__(self):
        self.robot_name = rospy.get_param('~robot', 'ugv0')
        robots = {robot['name']: robot for robot in rospy.get_param('/ground_robots', [])}
        if self.robot_name not in robots:
            raise RuntimeError('Unknown ground robot: %s' % self.robot_name)
        self.robot = robots[self.robot_name]
        self.nav = self.robot.get('navigation', {})
        self.goal_tol = float(self.nav.get('goal_tolerance_m', 0.25))
        self.rotate_threshold = float(self.nav.get('rotate_before_move_rad', 0.42))
        self.kv = float(self.nav.get('linear_gain', 0.65))
        self.kw = float(self.nav.get('angular_gain', 1.30))
        self.max_v = float(self.nav.get('max_linear_speed_mps', 0.38))
        self.max_w = float(self.nav.get('max_angular_speed_rps', 0.70))
        self.escape_heading = float(self.nav.get('blocked_escape_heading_rad', 0.25))
        self.lock = threading.RLock()
        self.pose = None
        self.goal = None
        self.route: List[PoseStamped] = []
        self.route_index = 0
        self.route_active = False
        self.blocked = False
        self.reported = False
        root = rospy.get_param(
            '/vlm_semantic_search',
            {},
        )

        color_cfg = root.get(
            'scheduler',
            {},
        ).get(
            'color_candidate_trigger',
            {},
        )

        self.color_hold_max_sec = float(
            color_cfg.get(
                'hold_max_sec',
                300.0,
            )
        )

        self.color_hold_active = False
        self.color_hold_id = ''
        self.color_hold_deadline_wall = 0.0
        self.task_finished = False
        self.cmd_pub = rospy.Publisher(self.robot['cmd_vel_topic'], Twist, queue_size=10)
        self.reached_pub = rospy.Publisher(self.robot['mission_reached_topic'], Bool, queue_size=5, latch=True)
        self.status_pub = rospy.Publisher('/%s/mission/status' % self.robot_name, String, queue_size=10, latch=True)
        self.reached_pub.publish(False)
        rospy.Subscriber(self.robot['global_pose_topic'], PoseStamped, self._pose_cb, queue_size=20)
        rospy.Subscriber(self.robot['mission_goal_topic'], PoseStamped, self._goal_cb, queue_size=5)
        rospy.Subscriber(self.robot.get('planned_path_topic', '/%s/search/planned_path' % self.robot_name),
                         Path, self._path_cb, queue_size=5)
        rospy.Subscriber(self.robot['blocked_topic'], Bool, self._blocked_cb, queue_size=10)
        rospy.Subscriber('/%s/vlm/observation_hold_command' % self.robot_name, String, self._color_hold_cb, queue_size=10,)
        rospy.Subscriber('/vlm/query_switch_cancel', String, self._query_switch_cancel_cb, queue_size=10)
        rospy.Subscriber('/experiment/task_finished', String, self._task_finished_cb, queue_size=1)
        self.control_timer = rospy.Timer(rospy.Duration(1.0 / 20.0), self._tick)
        rospy.loginfo('%s UGV A* route executor ready.', self.robot_name)

    def _pose_cb(self, msg):
        with self.lock:
            self.pose = msg

    def _goal_cb(self, msg):
        if (msg.header.frame_id or 'map') != 'map':
            rospy.logwarn('%s ignores goal in %s; expected map.', self.robot_name, msg.header.frame_id)
            return
        with self.lock:
            if self.task_finished:
                rospy.logwarn_throttle(5.0, '%s ignores goal after task completion.', self.robot_name)
                return
            # Legacy/manual final-goal command: intentionally clears any planned
            # route. Stage-5 normal operation uses _path_cb instead.
            self.route = []
            self.route_index = 0
            self.route_active = False
            self.goal = msg
            self.reported = False
            self.reached_pub.publish(False)
            self.status_pub.publish('tracking_direct_goal')
            rospy.loginfo('%s accepted direct ground goal [%.2f, %.2f].', self.robot_name,
                          msg.pose.position.x, msg.pose.position.y)

    def _path_cb(self, msg: Path):
        if (msg.header.frame_id or 'map') != 'map':
            rospy.logwarn('%s ignores path in %s; expected map.', self.robot_name, msg.header.frame_id)
            return
        if not msg.poses:
            rospy.logwarn('%s received empty A* path; holding current command.', self.robot_name)
            return
        with self.lock:
            if self.task_finished:
                rospy.logwarn_throttle(5.0, '%s ignores route after task completion.', self.robot_name)
                return
            self.route = list(msg.poses)
            self.route_index = 0
            self.route_active = True
            self.goal = self.route[0]
            self.reported = False
            self.reached_pub.publish(False)
            self.status_pub.publish('tracking_astar_route')
            rospy.loginfo('%s accepted A* route with %d waypoint(s).', self.robot_name, len(self.route))

    def _blocked_cb(self, msg):
        with self.lock:
            self.blocked = bool(msg.data)

    def _query_switch_cancel_cb(self, msg: String) -> None:
        try:
            notice = json.loads(msg.data)
        except Exception:
            return
        if not isinstance(notice, dict):
            return
        with self.lock:
            self.route = []
            self.route_index = 0
            self.route_active = False
            self.goal = None
            self.reported = False
            self.color_hold_active = False
            self.color_hold_id = ''
            self.color_hold_deadline_wall = 0.0
            self.reached_pub.publish(False)
            self.status_pub.publish('query_switch_cancel_hold')
        self._publish_zero()
        rospy.logwarn('%s cancelled active route due to target query switch v%s->v%s.',
                      self.robot_name, notice.get('old_query_version'), notice.get('new_query_version'))

    def _task_finished_cb(self, msg: String) -> None:
        try:
            event = json.loads(msg.data)
        except Exception:
            return
        if not isinstance(event, dict) or not bool(event.get('finished', False)):
            return
        with self.lock:
            if self.task_finished:
                return
            self.task_finished = True
            self.route = []
            self.route_index = 0
            self.route_active = False
            self.goal = None
            self.reported = True
            self.color_hold_active = False
            self.color_hold_id = ''
            self.color_hold_deadline_wall = 0.0
            self.reached_pub.publish(False)
            self.status_pub.publish('task_finished_hold')
        self._publish_zero()
        rospy.logwarn(
            '%s entered terminal hold: success=%s reason=%s.',
            self.robot_name,
            event.get('success'),
            event.get('finish_reason'),
        )

    def _color_hold_cb(self, msg: String) -> None:
        try:
            command = json.loads(msg.data)
        except Exception:
            return

        if not isinstance(command, dict):
            return

        hold_id = str(
            command.get('hold_id', '')
        )

        active = bool(
            command.get('active', False)
        )

        with self.lock:
            if active:
                self.color_hold_active = True
                self.color_hold_id = hold_id

                self.color_hold_deadline_wall = (
                    time.monotonic()
                    + self.color_hold_max_sec
                )

                rospy.logwarn(
                    '%s entered color observation hold id=%s.',
                    self.robot_name,
                    hold_id,
                )
                return

            # Old color events must not release a newer hold.
            if (
                self.color_hold_id
                and hold_id
                and self.color_hold_id != hold_id
            ):
                return

            self.color_hold_active = False
            self.color_hold_id = ''
            self.color_hold_deadline_wall = 0.0

            rospy.loginfo(
                '%s released color observation hold id=%s.',
                self.robot_name,
                hold_id,
            )


    def _color_hold_active_locked(self) -> bool:
        if not self.color_hold_active:
            return False

        if (
            self.color_hold_deadline_wall > 0.0
            and time.monotonic()
            >= self.color_hold_deadline_wall
        ):
            rospy.logwarn(
                '%s color observation hold expired; resuming route.',
                self.robot_name,
            )

            self.color_hold_active = False
            self.color_hold_id = ''
            self.color_hold_deadline_wall = 0.0

            return False

        return True

    @staticmethod
    def _wrap(angle):
        return math.atan2(math.sin(angle), math.cos(angle))

    @staticmethod
    def _distance(a: PoseStamped, b: PoseStamped) -> float:
        pa, pb = a.pose.position, b.pose.position
        return math.hypot(pa.x - pb.x, pa.y - pb.y)

    def _publish_zero(self):
        self.cmd_pub.publish(Twist())

    def _advance_route_locked(self) -> bool:
        """Advance all already reached intermediate waypoints.

        Returns True only when the final route endpoint has been reached.
        """
        if not self.route_active or self.pose is None:
            return False
        while self.route_index < len(self.route) and self._distance(self.pose, self.route[self.route_index]) <= self.goal_tol:
            self.route_index += 1
            if self.route_index < len(self.route):
                self.goal = self.route[self.route_index]
                rospy.loginfo('%s advances A* route waypoint %d/%d.', self.robot_name,
                              self.route_index + 1, len(self.route))
        if self.route_index >= len(self.route):
            self.route_active = False
            self.goal = self.route[-1]
            return True
        return False

    def _tick(self, _event):
        try:
            with self.lock:
                pose = self.pose
                task_finished = self.task_finished

                if pose is None:
                    status = 'WAIT_POSE'
                    goal = None
                    route_done = False
                    blocked = False
                    color_hold = False
                else:
                    color_hold = self._color_hold_active_locked()

                    # 颜色候选保持期间不推进 route_index。
                    if color_hold:
                        route_done = False
                        goal = self.goal
                        blocked = False
                    else:
                        route_done = self._advance_route_locked()
                        goal = self.goal
                        blocked = self.blocked

                    status = ''

            if task_finished:
                self._publish_zero()
                self.status_pub.publish('task_finished_hold')
                return

            if pose is None:
                self.status_pub.publish(status)
                self._publish_zero()
                return

            if color_hold:
                self._publish_zero()
                self.status_pub.publish(
                    'color_candidate_hold'
                )
                return

            if goal is None:
                self.status_pub.publish(
                    'HOLD_NO_GOAL'
                )
                self._publish_zero()
                return

            if route_done:
                self._publish_zero()

                if not self.reported:
                    self.reached_pub.publish(True)
                    self.reported = True

                    rospy.loginfo(
                        '%s reached final A* route goal.',
                        self.robot_name,
                    )

                self.status_pub.publish(
                    'route_reached_hold'
                )
                return

            p = pose.pose.position
            g = goal.pose.position

            dx = g.x - p.x
            dy = g.y - p.y

            distance = math.hypot(dx, dy)

            if distance <= self.goal_tol:
                if not self.route_active:
                    self._publish_zero()

                    if not self.reported:
                        self.reached_pub.publish(True)
                        self.reported = True

                        rospy.loginfo(
                            '%s reached direct ground goal.',
                            self.robot_name,
                        )

                    self.status_pub.publish(
                        'goal_reached_hold'
                    )

                return

            q = pose.pose.orientation

            yaw = euler_from_quaternion([
                q.x,
                q.y,
                q.z,
                q.w,
            ])[2]

            target_yaw = math.atan2(
                dy,
                dx,
            )

            error = self._wrap(
                target_yaw - yaw
            )

            w = max(
                -self.max_w,
                min(
                    self.max_w,
                    self.kw * error,
                ),
            )

            if blocked:
                if abs(error) >= self.escape_heading:
                    cmd = Twist()
                    cmd.angular.z = w

                    self.cmd_pub.publish(cmd)

                    self.status_pub.publish(
                        'blocked_rotate_to_route'
                    )
                else:
                    self._publish_zero()

                    self.status_pub.publish(
                        'blocked_hold_replan'
                    )

                return

            cmd = Twist()
            cmd.angular.z = w

            if abs(error) > self.rotate_threshold:
                cmd.linear.x = 0.0

                self.status_pub.publish(
                    (
                        'rotate_to_route_waypoint'
                        if self.route_active
                        else 'rotate_to_goal'
                    )
                )
            else:
                cmd.linear.x = min(
                    self.max_v,
                    max(
                        0.06,
                        self.kv * distance,
                    ),
                )

                self.status_pub.publish(
                    (
                        'tracking_astar_route'
                        if self.route_active
                        else 'tracking_direct_goal'
                    )
                )

            self.cmd_pub.publish(cmd)

            rospy.loginfo_throttle(
                2.0,
                '%s cmd_vel: v=%.2f, w=%.2f, distance=%.2f.',
                self.robot_name,
                cmd.linear.x,
                cmd.angular.z,
                distance,
            )

        except Exception as exc:
            rospy.logerr_throttle(
                2.0,
                '%s waypoint-control error: %r',
                self.robot_name,
                exc,
            )

            self._publish_zero()

            self.status_pub.publish(
                'CONTROL_ERROR'
            )


def main():
    rospy.init_node('ugv_waypoint_executor')
    UGVWaypointExecutor()
    rospy.spin()


if __name__ == '__main__':
    main()
